// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var overview = {
  name: "NexCare",
  tagline: "Real-Time Monitoring. Real-Life Rescue.",
  description: "NexCare is a continuous healthcare platform powered by AI, doctors, and real-time patient data. Wearables and connected apps monitor vitals 24/7, AI flags early warning signs, doctors and nutritionists engage proactively, medications are delivered via partner pharmacies, and emergency services are triggered when seconds matter.",
  poweredBy: "Nexus X Industries",
  website: "https://continuous-health-flow.lovable.app"
};
var get_overview_default = defineTool({
  name: "get_overview",
  title: "Get NexCare overview",
  description: "Return a short overview of NexCare: name, tagline, description, and website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(overview, null, 2) }],
    structuredContent: overview
  })
});

// src/lib/mcp/tools/get-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var services = [
  { name: "Telehealth", description: "On-demand video and chat consultations with licensed physicians, specialists, and mental health professionals \u2014 from anywhere.", features: ["24/7 availability", "Specialist referrals", "Prescription delivery"] },
  { name: "Nutrition Planning", description: "Personalized meal plans and dietary guidance from certified nutritionists, tailored to your health goals and conditions.", features: ["Custom meal plans", "Allergy-aware", "Progress tracking"] },
  { name: "Diagnostics", description: "At-home lab kits and integrated diagnostic tools that deliver accurate results directly to your care team.", features: ["Home sample collection", "Fast turnaround", "Doctor-reviewed results"] },
  { name: "Wellness Programs", description: "Holistic wellness plans combining fitness, mindfulness, and preventive care \u2014 designed for long-term health outcomes.", features: ["Fitness coaching", "Stress management", "Sleep optimization"] },
  { name: "Chronic Care Management", description: "Continuous monitoring and proactive management for diabetes, hypertension, asthma, and other chronic conditions.", features: ["Daily vitals tracking", "Medication reminders", "Care team alerts"] },
  { name: "Mental Health", description: "Confidential therapy sessions, cognitive behavioral tools, and AI-driven mood tracking for emotional well-being.", features: ["Licensed therapists", "CBT tools", "Mood analytics"] }
];
var get_services_default = defineTool2({
  name: "get_services",
  title: "Get NexCare services",
  description: "List NexCare's care services with their descriptions and key features.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/get-solution-flow.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var steps = [
  { step: 1, label: "Monitor", description: "Wearable + app track vitals continuously" },
  { step: 2, label: "Detect", description: "AI analyses data for early warning signs" },
  { step: 3, label: "Consult", description: "Doctors & nutritionists engage proactively" },
  { step: 4, label: "Treat", description: "Pharmacy delivery & medication tracking" },
  { step: 5, label: "Rescue", description: "Emergency integration when seconds matter" }
];
var get_solution_flow_default = defineTool3({
  name: "get_solution_flow",
  title: "Get NexCare care pipeline",
  description: "Return NexCare's 5-step continuous-care pipeline: Monitor, Detect, Consult, Treat, Rescue.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(steps, null, 2) }],
    structuredContent: { steps }
  })
});

// src/lib/mcp/tools/get-partners.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var partners = [
  { audience: "Freelance Doctors", pitch: "Earn flexibly by joining the NexCare network. Set your hours, receive AI-matched referrals, and consult remotely." },
  { audience: "Insurance & HMOs", pitch: "Reduce emergency claims with continuous monitoring. Access population-level analytics and preventive care tools." },
  { audience: "Pharmacies", pitch: "Receive verified e-prescriptions directly. Manage inventory and fulfil deliveries through the NexCare marketplace." }
];
var get_partners_default = defineTool4({
  name: "get_partners",
  title: "Get NexCare partner offerings",
  description: "Return the value proposition for each NexCare partner type (doctors, insurers/HMOs, pharmacies).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(partners, null, 2) }],
    structuredContent: { partners }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "nexcare-mcp",
  title: "NexCare",
  version: "0.1.0",
  instructions: "Tools for the NexCare continuous-healthcare platform. Use `get_overview` for a quick summary, `get_services` for care service details, `get_solution_flow` for the 5-step care pipeline, and `get_partners` for partner (doctor, insurer, pharmacy) offerings. All data is public marketing information.",
  tools: [get_overview_default, get_services_default, get_solution_flow_default, get_partners_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
